config/routes.rb
Rails.application.routes.draw do
  get 'toppages/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :facilities
  resources :buildings
  resources :users, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :last_updated_user, :class_name => "User"

  has_many :relationships, :dependent => :destroy

  validates :building_number, presence: true, uniqueness: true
end

app/models/facility.rb
class Facility < ApplicationRecord
  belongs_to :last_updated_user, :class_name => "User"

  has_many :relationships, :dependent => :destroy

  validates :facility_number, presence: true, uniqueness: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :facility
  belongs_to :building
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :facilities, :class_name => "Facility", :foreign_key => 'last_updated_user_id'
  has_many :buildings, :class_name => "Building", :foreign_key => 'last_updated_user_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :require_user_logged_in

  def index
    @buildings = Building.all
    @total_floor_area = @buildings.sum(:floor_area)
  end

  def show
    @building = Building.find(params[:id])
    @facility = Facility.find_by(id: @building.facility_id)
    @user = User.find(@building.last_updated_user_id)
  end

  def new
    @building = Building.new
  end

  def create
    @building = Building.new(building_params)
    @building.relationships.build(facility_id: building_params[:facility_id])

    if @building.save
      flash[:success] = '建物が正常に作成されました'
      redirect_to @building
    else
      flash.now[:danger] = '建物が作成されませんでした'
      render :new
    end
  end

  def edit
    @building = Building.find(params[:id])
    #@user = User.find(@building.last_updated_user_id)
  end

  def update
    @building = Building.find(params[:id])
    @building.relationships.build(facility_id: building_params[:facility_id])

    # 更新前の関連インスタンスを削除
    #（validation エラーでも削除されるため、存在している場合のみ削除）
    previous_relationship = Relationship.find_by( \
      facility_id: params[:previous_facility_id], \
      building_id: params[:id] \
    )
    previous_relationship.destroy if !!previous_relationship

    if @building.update(building_params)
      flash[:success] = '建物が正常に更新されました'
      redirect_to @building
    else
      # 削除した関連インスタンスを再作成
      Relationship.create( \
        facility_id: params[:previous_facility_id], \
        building_id: params[:id]
      )
      flash.now[:danger] = '建物が更新されませんでした'
      render :edit
    end
  end

  def destroy
    @building = Building.find(params[:id])
    @building.destroy

    flash[:success] = '建物は正常に削除されました'
    redirect_to buildings_url
  end

  private

  # Strong Parameter
  def building_params
    params.require(:building).permit(:building_number, :name, :facility_id, :construction_year, :floor_area, :last_updated_user_id)
  end

end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :require_user_logged_in

  def index
    @facilities = Facility.all
    @total_floor_area = @facilities.sum(:floor_area)
  end
  
  def show
    @facility = Facility.find(params[:id])
    @user = User.find(@facility.last_updated_user_id)
  end
  
  def new
    @facility = Facility.new
  end
  
  def create
    @facility = Facility.new(facility_params)
    
    if @facility.save
      flash[:success] = '施設が正常に作成されました'
      redirect_to @facility
    else
      flash.now[:danger] = '施設が作成されませんでした'
      render :new
    end
  end
  
  def edit
    @facility = Facility.find(params[:id])
  end

  def update
    @facility = Facility.find(params[:id])
    
    if @facility.update(facility_params)
      flash[:success] = '施設が正常に更新されました'
      redirect_to @facility
    else
      flash.now[:danger] = '施設が更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    @facility = Facility.find(params[:id])

    if !!Relationship.find_by(facility_id: @facility)
      flash[:danger] = '先に関連付けされている建物を削除してください。'
      redirect_to @facility
    else
      @facility.destroy
      flash[:success] = '施設は正常に削除されました。'
      redirect_to facilities_url
    end
  end
  
  private
    
  # Strong Parameter
  def facility_params
    params.require(:facility).permit(:facility_number, :name, :district, :address, :facility_type, :floor_area, :division_in_charge, :last_updated_user_id)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def destroy
    @relationship = Relationship.find(params[:id])
    @relationsihp.destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to facilities_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.all.page(params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to facilities_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/buildings/edit.html.erb
<h1>建物編集</h1>

<%= form_for(@building) do |f| %>
  <%= render 'layouts/error_messages', model: @building %>

  <%= f.label :building_number, '建物ID' %>
  <%= f.text_field :building_number %><br>
  <%= f.label :name, '建物名' %>
  <%= f.text_field :name %><br>
  <%= f.label :facility_id, '対象施設' %>
  <%= f.collection_select :facility_id, Facility.all, :id, :name %><br>
  <%= f.label :construction_year, '施行年度' %>
  <%= f.text_field :construction_year %><br>
  <%= f.label :floor_area, '延床面積' %>
  <%= f.text_field :floor_area %>㎡<br>
  <%= f.hidden_field :last_updated_user_id, :value => current_user.id %>
  <%= hidden_field_tag :previous_facility_id , @building.facility_id %>

  <%= f.submit '確定' %>
<% end %>

app/views/buildings/index.html.erb
<h1>建物一覧</h1>
<h3>総延床面積：<%= @total_floor_area %>㎡</h3>

<%= link_to '新規建物', new_building_path %>

<ul>
  <% @buildings.each do |building| %>
    <li><%= link_to building.building_number, building %>   <%= building.name %></li>
  <% end %>
</ul>

app/views/buildings/new.html.erb
<h1>建物作成</h1>

<%= form_for(@building) do |f| %>
  <%= render 'layouts/error_messages', model: @building %>
  
  <%= f.label :building_number, '建物ID' %>
  <%= f.text_field :building_number %><br>
  <%= f.label :name, '建物名' %>
  <%= f.text_field :name %><br>
  <%= f.label :facility_id, '対象施設' %>
  <%= f.collection_select :facility_id, Facility.all, :id, :name %><br>
  <%= f.label :construction_year, '施行年度' %>
  <%= f.text_field :construction_year %><br>
  <%= f.label :floor_area, '延床面積' %>
  <%= f.text_field :floor_area %>㎡<br>
  <%= f.hidden_field :last_updated_user_id, :value => current_user.id %>

  <%= f.submit '作成' %>
<% end %>

app/views/buildings/show.html.erb
<h1>建物詳細</h1>

<p>建物ID <%= @building.building_number %></p>
<p>建物名 <%= @building.name %></p>
<p>対象施設 <%= @facility.facility_number %>:<%= @facility.name %></p>
<p>施行年度 <%= @building.construction_year %></p>
<p>延床面積 <%= @building.floor_area %>㎡</p>
<p>最終更新者 <%= @user.name %></p>

<%= link_to '編集', edit_building_path(@building) %>
<%= link_to '削除', @building, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/facilities/edit.html.erb
<h1>施設編集</h1>

<%= form_for(@facility) do |f| %>
  <%= render 'layouts/error_messages', model: @facility %>

  <%= f.label :facility_number, '施設ID' %>
  <%= f.text_field :facility_number %><br>
  <%= f.label :name, '施設名' %>
  <%= f.text_field :name %><br>
  <%= f.label :district, '地区' %>
  <%= f.text_field :district %><br>
  <%= f.label :address, '住所' %>
  <%= f.text_field :address %><br>
  <%= f.label :facility_type, '施設分類' %>
  <%= f.text_field :facility_type %><br>
  <%= f.label :floor_area, '延床面積' %>
  <%= f.text_field :floor_area %>㎡<br>
  <%= f.label :division_in_charge, '担当課' %>
  <%= f.text_field :division_in_charge %><br>
  <%= f.hidden_field :last_updated_user_id, :value => current_user.id %>

  <%= f.submit '確定' %>
<% end %>

app/views/facilities/index.html.erb
<h1>施設一覧</h1>
<h3>総延床面積：<%= @total_floor_area %>㎡</h3>

<%= link_to '新規施設', new_facility_path %>

<ul>
  <% @facilities.each do |facility| %>
    <li><%= link_to facility.facility_number, facility %>   <%= facility.name %></li>
  <% end %>
</ul>

app/views/facilities/new.html.erb
<h1>施設作成</h1>

<%= form_for(@facility) do |f| %>
  <%= render 'layouts/error_messages', model: @facility %>

  <%= f.label :facility_number, '施設ID' %>
  <%= f.text_field :facility_number %><br>
  <%= f.label :name, '施設名' %>
  <%= f.text_field :name %><br>
  <%= f.label :district, '地区' %>
  <%= f.text_field :district %><br>
  <%= f.label :address, '住所' %>
  <%= f.text_field :address %><br>
  <%= f.label :facility_type, '施設分類' %>
  <%= f.text_field :facility_type %><br>
  <%= f.label :floor_area, '延床面積' %>
  <%= f.text_field :floor_area %>㎡<br>
  <%= f.label :division_in_charge, '担当課' %>
  <%= f.text_field :division_in_charge %><br>
  <%= f.hidden_field :last_updated_user_id, :value => current_user.id %>

  <%= f.submit '作成' %>
<% end %>

app/views/facilities/show.html.erb
<h1>施設詳細</h1>

<p>施設ID <%= @facility.facility_number %></p>
<p>施設名 <%= @facility.name %></p>
<p>地区 <%= @facility.district %></p>
<p>住所 <%= @facility.address %></p>
<p>施設分類 <%= @facility.facility_type %></p>
<p>延床面積 <%= @facility.floor_area %>㎡</p>
<p>担当課 <%= @facility.division_in_charge %></p>
<p>最終更新者 <%= @user.name %></p>

<%= link_to '編集', edit_facility_path(@facility) %>
<%= link_to '削除', @facility, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to '施設一覧', facilities_url %></li>
          <li><%= link_to '建物一覧', buildings_url %></li>
        </ul>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'ユーザ一覧', users_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'ユーザ登録', signup_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>PublicFacility</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
    
      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ： <%= current_user.name %></p>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>公共施設 調査票</h1>
      <%= link_to 'ユーザ登録', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>ユーザ一覧</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="text-center">
  <h1>ユーザ登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
    
      <div class="form-group">
        <%= f.label :name, 'ユーザ名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード確認' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'ユーザ登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>